#!/usr/bin/env python3
"""One-shot: add a `classes` column to docs/spell-master-list.csv.

Sources of truth, in order:
  - SRD 5.2.1 spell headers (CC-BY) — every SRD spell's header line
    carries its base-class list, e.g. "Level 2 Abjuration (Bard, Cleric)".
  - "Available for" comments saved in built f_*.yaml files (PHB-only
    spells captured from DDB pastes).
  - 2024 PHB class lists from model knowledge for the remaining
    PHB-only spells — rows where confidence is lower carry a
    "classes: verify" note for manual spot-checking.

Column semantics: BASE classes only (the 2024 spell-header parenthetical).
Subclass grants (domain spells, Oath lists, patron expansions) are a
separate Phase-3 mechanism and stay in the per-feature YAML comments.
"""
import csv
from pathlib import Path

MASTER = Path(__file__).resolve().parent.parent / "docs" / "spell-master-list.csv"

C = {
    # ---- Level 0 ----
    "Acid Splash": "sorcerer;wizard",
    "Blade Ward": "bard;sorcerer;warlock;wizard",
    "Chill Touch": "sorcerer;warlock;wizard",
    "Dancing Lights": "bard;sorcerer;wizard",
    "Druidcraft": "druid",
    "Eldritch Blast": "warlock",
    "Elementalism": "druid;sorcerer;wizard",
    "Fire Bolt": "sorcerer;wizard",
    "Friends": "bard;sorcerer;warlock;wizard",
    "Guidance": "cleric;druid",
    "Light": "bard;cleric;sorcerer;wizard",
    "Mage Hand": "bard;sorcerer;warlock;wizard",
    "Mending": "bard;cleric;druid;sorcerer;wizard",
    "Message": "bard;druid;sorcerer;wizard",
    "Mind Sliver": "sorcerer;warlock;wizard",
    "Minor Illusion": "bard;sorcerer;warlock;wizard",
    "Poison Spray": "druid;sorcerer;warlock;wizard",
    "Prestidigitation": "bard;sorcerer;warlock;wizard",
    "Produce Flame": "druid",
    "Ray of Frost": "sorcerer;wizard",
    "Resistance": "cleric;druid",
    "Sacred Flame": "cleric",
    "Shillelagh": "druid",
    "Shocking Grasp": "sorcerer;wizard",
    "Sorcerous Burst": "sorcerer",
    "Spare the Dying": "cleric;druid",
    "Starry Wisp": "bard;druid",
    "Thaumaturgy": "cleric",
    "Thorn Whip": "druid",
    "Thunderclap": "bard;druid;sorcerer;warlock;wizard",
    "Toll the Dead": "cleric;warlock;wizard",
    "True Strike": "bard;sorcerer;warlock;wizard",
    "Vicious Mockery": "bard",
    "Word of Radiance": "cleric",
    # ---- Level 1 ----
    "Alarm": "ranger;wizard",
    "Animal Friendship": "bard;druid;ranger",
    "Armor of Agathys": "warlock",
    "Arms of Hadar": "warlock",
    "Bane": "bard;cleric",
    "Bless": "cleric;paladin",
    "Burning Hands": "sorcerer;wizard",
    "Charm Person": "bard;druid;sorcerer;warlock;wizard",
    "Chromatic Orb": "sorcerer;wizard",
    "Color Spray": "bard;sorcerer;wizard",
    "Command": "bard;cleric;paladin",
    "Compelled Duel": "paladin",
    "Comprehend Languages": "bard;sorcerer;warlock;wizard",
    "Create or Destroy Water": "cleric;druid",
    "Cure Wounds": "bard;cleric;druid;paladin;ranger",
    "Detect Evil and Good": "cleric;paladin",
    "Detect Magic": "bard;cleric;druid;paladin;ranger;sorcerer;warlock;wizard",
    "Detect Poison and Disease": "cleric;druid;paladin;ranger",
    "Disguise Self": "bard;sorcerer;wizard",
    "Dissonant Whispers": "bard",
    "Divine Favor": "paladin",
    "Divine Smite": "paladin",
    "Ensnaring Strike": "ranger",
    "Entangle": "druid;ranger",
    "Expeditious Retreat": "sorcerer;warlock;wizard",
    "Faerie Fire": "bard;druid",
    "False Life": "sorcerer;wizard",
    "Feather Fall": "bard;sorcerer;wizard",
    "Find Familiar": "wizard",
    "Fog Cloud": "druid;ranger;sorcerer;wizard",
    "Goodberry": "druid;ranger",
    "Grease": "sorcerer;wizard",
    "Guiding Bolt": "cleric",
    "Hail of Thorns": "ranger",
    "Healing Word": "bard;cleric;druid",
    "Hellish Rebuke": "warlock",
    "Heroism": "bard;paladin",
    "Hex": "warlock",
    "Hunter's Mark": "ranger",
    "Ice Knife": "druid;sorcerer;wizard",
    "Identify": "bard;wizard",
    "Illusory Script": "bard;warlock;wizard",
    "Inflict Wounds": "cleric",
    "Jump": "druid;ranger;sorcerer;wizard",
    "Longstrider": "bard;druid;ranger;wizard",
    "Mage Armor": "sorcerer;wizard",
    "Magic Missile": "sorcerer;wizard",
    "Protection from Evil and Good": "cleric;druid;paladin;warlock;wizard",
    "Purify Food and Drink": "cleric;druid;paladin",
    "Ray of Sickness": "sorcerer;wizard",
    "Sanctuary": "cleric",
    "Searing Smite": "paladin",
    "Shield": "sorcerer;wizard",
    "Shield of Faith": "cleric;paladin",
    "Silent Image": "bard;sorcerer;wizard",
    "Sleep": "bard;sorcerer;wizard",
    "Speak with Animals": "bard;druid;ranger;warlock",
    "Tasha's Hideous Laughter": "bard;warlock;wizard",
    "Tenser's Floating Disk": "wizard",
    "Thunderous Smite": "paladin",
    "Thunderwave": "bard;druid;sorcerer;wizard",
    "Unseen Servant": "bard;warlock;wizard",
    "Witch Bolt": "sorcerer;warlock;wizard",
    "Wrathful Smite": "paladin",
    # ---- Level 2 ----
    "Aid": "bard;cleric;druid;paladin;ranger",
    "Alter Self": "sorcerer;wizard",
    "Animal Messenger": "bard;druid;ranger",
    "Arcane Lock": "wizard",
    "Arcane Vigor": "sorcerer;wizard",
    "Augury": "cleric;druid;wizard",
    "Barkskin": "druid;ranger",
    "Beast Sense": "druid;ranger",
    "Blindness/Deafness": "bard;sorcerer;wizard",
    "Blur": "sorcerer;wizard",
    "Calm Emotions": "bard;cleric",
    "Cloud of Daggers": "bard;sorcerer;warlock;wizard",
    "Continual Flame": "cleric;druid;wizard",
    "Cordon of Arrows": "ranger",
    "Crown of Madness": "bard;sorcerer;warlock;wizard",
    "Darkness": "sorcerer;warlock;wizard",
    "Darkvision": "druid;ranger;sorcerer;wizard",
    "Detect Thoughts": "bard;sorcerer;wizard",
    "Dragon's Breath": "sorcerer;wizard",
    "Enhance Ability": "bard;cleric;druid;ranger;sorcerer;wizard",
    "Enlarge/Reduce": "bard;druid;sorcerer;wizard",
    "Enthrall": "bard;warlock",
    "Find Steed": "paladin",
    "Find Traps": "cleric;druid;ranger",
    "Flame Blade": "druid;sorcerer",
    "Flaming Sphere": "druid;sorcerer;wizard",
    "Gentle Repose": "cleric;paladin;wizard",
    "Gust of Wind": "druid;ranger;sorcerer;wizard",
    "Heat Metal": "bard;druid",
    "Hold Person": "bard;cleric;druid;sorcerer;warlock;wizard",
    "Invisibility": "bard;sorcerer;warlock;wizard",
    "Knock": "bard;sorcerer;wizard",
    "Lesser Restoration": "bard;cleric;druid;paladin;ranger",
    "Levitate": "sorcerer;wizard",
    "Locate Animals or Plants": "bard;druid;ranger",
    "Locate Object": "bard;cleric;druid;paladin;ranger;wizard",
    "Magic Mouth": "bard;wizard",
    "Magic Weapon": "paladin;ranger;sorcerer;wizard",
    "Melf's Acid Arrow": "wizard",
    "Mind Spike": "sorcerer;warlock;wizard",
    "Mirror Image": "bard;sorcerer;warlock;wizard",
    "Misty Step": "sorcerer;warlock;wizard",
    "Moonbeam": "druid",
    "Nystul's Magic Aura": "wizard",
    "Pass without Trace": "druid;ranger",
    "Phantasmal Force": "bard;sorcerer;wizard",
    "Prayer of Healing": "cleric;paladin",
    "Protection from Poison": "cleric;druid;paladin;ranger",
    "Ray of Enfeeblement": "warlock;wizard",
    "Rope Trick": "wizard",
    "Scorching Ray": "sorcerer;wizard",
    "See Invisibility": "bard;sorcerer;wizard",
    "Shatter": "bard;sorcerer;warlock;wizard",
    "Shining Smite": "paladin",
    "Silence": "bard;cleric;ranger",
    "Spider Climb": "sorcerer;warlock;wizard",
    "Spike Growth": "druid;ranger",
    "Spiritual Weapon": "cleric",
    "Suggestion": "bard;sorcerer;warlock;wizard",
    "Summon Beast": "druid;ranger",
    "Warding Bond": "cleric",
    "Web": "sorcerer;wizard",
    "Zone of Truth": "bard;cleric;paladin",
    # ---- Level 3 ----
    "Animate Dead": "cleric;wizard",
    "Aura of Vitality": "cleric;paladin",
    "Beacon of Hope": "cleric",
    "Bestow Curse": "bard;cleric;wizard",
    "Blinding Smite": "paladin",
    "Blink": "sorcerer;wizard",
    "Call Lightning": "druid",
    "Clairvoyance": "bard;cleric;sorcerer;wizard",
    "Conjure Animals": "druid;ranger",
    "Conjure Barrage": "ranger",
    "Counterspell": "sorcerer;warlock;wizard",
    "Create Food and Water": "cleric;paladin",
    "Crusader's Mantle": "paladin",
    "Daylight": "cleric;druid;paladin;ranger;sorcerer",
    "Dispel Magic": "bard;cleric;druid;paladin;ranger;sorcerer;warlock;wizard",
    "Elemental Weapon": "druid;paladin;ranger",
    "Fear": "bard;sorcerer;warlock;wizard",
    "Feign Death": "bard;cleric;druid;wizard",
    "Fireball": "sorcerer;wizard",
    "Fly": "sorcerer;warlock;wizard",
    "Gaseous Form": "sorcerer;warlock;wizard",
    "Glyph of Warding": "bard;cleric;wizard",
    "Haste": "sorcerer;wizard",
    "Hunger of Hadar": "warlock",
    "Hypnotic Pattern": "bard;sorcerer;warlock;wizard",
    "Leomund's Tiny Hut": "bard;wizard",
    "Lightning Arrow": "ranger",
    "Lightning Bolt": "sorcerer;wizard",
    "Magic Circle": "cleric;paladin;warlock;wizard",
    "Major Image": "bard;sorcerer;warlock;wizard",
    "Mass Healing Word": "bard;cleric",
    "Meld into Stone": "cleric;druid;ranger",
    "Nondetection": "bard;ranger;wizard",
    "Phantom Steed": "wizard",
    "Plant Growth": "bard;druid;ranger",
    "Protection from Energy": "cleric;druid;ranger;sorcerer;wizard",
    "Remove Curse": "cleric;paladin;warlock;wizard",
    "Revivify": "cleric;druid;paladin;ranger",
    "Sending": "bard;cleric;wizard",
    "Sleet Storm": "druid;sorcerer;wizard",
    "Slow": "bard;sorcerer;wizard",
    "Speak with Dead": "bard;cleric;wizard",
    "Speak with Plants": "bard;druid;ranger",
    "Spirit Guardians": "cleric",
    "Stinking Cloud": "bard;sorcerer;wizard",
    "Summon Fey": "druid;ranger;warlock;wizard",
    "Summon Undead": "warlock;wizard",
    "Tongues": "bard;cleric;sorcerer;warlock;wizard",
    "Vampiric Touch": "sorcerer;warlock;wizard",
    "Water Breathing": "druid;ranger;sorcerer;wizard",
    "Water Walk": "cleric;druid;ranger;sorcerer",
    "Wind Wall": "druid;ranger",
    # ---- Level 4 ----
    "Arcane Eye": "wizard",
    "Aura of Life": "cleric;paladin",
    "Aura of Purity": "cleric;paladin",
    "Banishment": "cleric;paladin;sorcerer;warlock;wizard",
    "Blight": "druid;sorcerer;warlock;wizard",
    "Charm Monster": "bard;druid;sorcerer;warlock;wizard",
    "Compulsion": "bard",
    "Confusion": "bard;druid;sorcerer;wizard",
    "Conjure Minor Elementals": "druid;wizard",
    "Conjure Woodland Beings": "druid",
    "Control Water": "cleric;druid;wizard",
    "Death Ward": "cleric;paladin",
    "Dimension Door": "bard;sorcerer;warlock;wizard",
    "Divination": "cleric;druid;wizard",
    "Dominate Beast": "druid;ranger;sorcerer",
    "Evard's Black Tentacles": "wizard",
    "Fabricate": "wizard",
    "Fire Shield": "druid;sorcerer;wizard",
    "Fount of Moonlight": "bard;druid",
    "Freedom of Movement": "bard;cleric;druid;ranger",
    "Giant Insect": "druid",
    "Grasping Vine": "druid;ranger",
    "Greater Invisibility": "bard;sorcerer;wizard",
    "Guardian of Faith": "cleric",
    "Hallucinatory Terrain": "bard;druid;warlock;wizard",
    "Ice Storm": "druid;sorcerer;wizard",
    "Leomund's Secret Chest": "wizard",
    "Locate Creature": "bard;cleric;druid;paladin;ranger;wizard",
    "Mordenkainen's Faithful Hound": "wizard",
    "Mordenkainen's Private Sanctum": "wizard",
    "Otiluke's Resilient Sphere": "wizard",
    "Phantasmal Killer": "bard;sorcerer;wizard",
    "Polymorph": "bard;druid;sorcerer;wizard",
    "Sickening Radiance": "sorcerer;warlock;wizard",
    "Staggering Smite": "paladin",
    "Stone Shape": "cleric;druid;wizard",
    "Stoneskin": "druid;ranger;sorcerer;wizard",
    "Summon Aberration": "warlock;wizard",
    "Summon Construct": "wizard",
    "Summon Elemental": "druid;ranger;wizard",
    "Vitriolic Sphere": "sorcerer;wizard",
    "Wall of Fire": "druid;sorcerer;wizard",
    # ---- Level 5 ----
    "Animate Objects": "bard;sorcerer;wizard",
    "Antilife Shell": "druid",
    "Awaken": "bard;druid",
    "Banishing Smite": "paladin",
    "Bigby's Hand": "sorcerer;wizard",
    "Circle of Power": "cleric;paladin;wizard",
    "Cloudkill": "sorcerer;wizard",
    "Commune": "cleric",
    "Commune with Nature": "druid;ranger",
    "Cone of Cold": "druid;sorcerer;wizard",
    "Conjure Elemental": "druid;wizard",
    "Conjure Volley": "ranger",
    "Contact Other Plane": "warlock;wizard",
    "Contagion": "cleric;druid",
    "Creation": "sorcerer;wizard",
    "Destructive Wave": "paladin",
    "Dispel Evil and Good": "cleric;paladin",
    "Dominate Person": "bard;sorcerer;wizard",
    "Dream": "bard;warlock;wizard",
    "Flame Strike": "cleric",
    "Geas": "bard;cleric;druid;paladin;wizard",
    "Greater Restoration": "bard;cleric;druid;paladin;ranger",
    "Hallow": "cleric",
    "Hold Monster": "bard;sorcerer;warlock;wizard",
    "Insect Plague": "cleric;druid;sorcerer",
    "Jallarzi's Storm of Radiance": "warlock;wizard",
    "Legend Lore": "bard;cleric;wizard",
    "Mass Cure Wounds": "bard;cleric;druid",
    "Mislead": "bard;warlock;wizard",
    "Modify Memory": "bard;wizard",
    "Passwall": "wizard",
    "Planar Binding": "bard;cleric;druid;warlock;wizard",
    "Raise Dead": "bard;cleric;paladin",
    "Rary's Telepathic Bond": "bard;wizard",
    "Reincarnate": "druid",
    "Scrying": "bard;cleric;druid;warlock;wizard",
    "Seeming": "bard;sorcerer;wizard",
    "Steel Wind Strike": "ranger;wizard",
    "Summon Celestial": "cleric;paladin",
    "Summon Dragon": "wizard",
    "Swift Quiver": "ranger",
    "Synaptic Static": "bard;sorcerer;warlock;wizard",
    "Telekinesis": "sorcerer;wizard",
    "Teleportation Circle": "bard;sorcerer;wizard",
    "Tree Stride": "druid;ranger",
    "Wall of Force": "wizard",
    "Wall of Stone": "druid;sorcerer;wizard",
    "Yolande's Regal Presence": "bard;wizard",
    # ---- Level 6 ----
    "Arcane Gate": "sorcerer;warlock;wizard",
    "Blade Barrier": "cleric",
    "Chain Lightning": "sorcerer;wizard",
    "Circle of Death": "sorcerer;warlock;wizard",
    "Conjure Fey": "druid;warlock",
    "Contingency": "wizard",
    "Create Undead": "cleric;warlock;wizard",
    "Disintegrate": "sorcerer;wizard",
    "Drawmij's Instant Summons": "wizard",
    "Eyebite": "bard;sorcerer;warlock;wizard",
    "Find the Path": "bard;cleric;druid",
    "Flesh to Stone": "druid;sorcerer;wizard",
    "Forbiddance": "cleric",
    "Globe of Invulnerability": "sorcerer;wizard",
    "Guards and Wards": "bard;wizard",
    "Harm": "cleric",
    "Heal": "cleric;druid",
    "Heroes' Feast": "cleric;druid",
    "Magic Jar": "wizard",
    "Mass Suggestion": "bard;sorcerer;warlock;wizard",
    "Move Earth": "druid;sorcerer;wizard",
    "Otiluke's Freezing Sphere": "sorcerer;wizard",
    "Otto's Irresistible Dance": "bard;wizard",
    "Planar Ally": "cleric",
    "Programmed Illusion": "bard;wizard",
    "Summon Fiend": "warlock;wizard",
    "Sunbeam": "cleric;druid;sorcerer;wizard",
    "Tasha's Bubbling Cauldron": "warlock;wizard",
    "Transport via Plants": "druid",
    "True Seeing": "bard;cleric;sorcerer;warlock;wizard",
    "Wall of Ice": "wizard",
    "Wall of Thorns": "druid",
    "Wind Walk": "druid",
    "Word of Recall": "cleric",
    # ---- Level 7 ----
    "Conjure Celestial": "cleric",
    "Delayed Blast Fireball": "sorcerer;wizard",
    "Divine Word": "cleric",
    "Etherealness": "bard;cleric;sorcerer;warlock;wizard",
    "Finger of Death": "sorcerer;warlock;wizard",
    "Fire Storm": "cleric;druid;sorcerer",
    "Forcecage": "bard;warlock;wizard",
    "Mirage Arcane": "bard;druid;wizard",
    "Mordenkainen's Magnificent Mansion": "bard;wizard",
    "Mordenkainen's Sword": "bard;wizard",
    "Plane Shift": "cleric;druid;sorcerer;warlock;wizard",
    "Power Word Fortify": "bard;cleric",
    "Prismatic Spray": "bard;sorcerer;wizard",
    "Project Image": "bard;wizard",
    "Regenerate": "bard;cleric;druid",
    "Resurrection": "bard;cleric",
    "Reverse Gravity": "druid;sorcerer;wizard",
    "Sequester": "wizard",
    "Simulacrum": "wizard",
    "Symbol": "bard;cleric;druid;wizard",
    "Teleport": "bard;sorcerer;wizard",
    # ---- Level 8 ----
    "Animal Shapes": "druid",
    "Antimagic Field": "cleric;wizard",
    "Antipathy/Sympathy": "bard;druid;wizard",
    "Befuddlement": "bard;druid;warlock;wizard",
    "Clone": "wizard",
    "Control Weather": "cleric;druid;wizard",
    "Demiplane": "sorcerer;warlock;wizard",
    "Dominate Monster": "bard;sorcerer;warlock;wizard",
    "Earthquake": "cleric;druid;sorcerer",
    "Glibness": "bard;warlock",
    "Holy Aura": "cleric",
    "Incendiary Cloud": "druid;sorcerer;wizard",
    "Maze": "wizard",
    "Mind Blank": "bard;wizard",
    "Power Word Stun": "bard;sorcerer;warlock;wizard",
    "Sunburst": "cleric;druid;sorcerer;wizard",
    "Telepathy": "wizard",
    "Tsunami": "druid",
    # ---- Level 9 ----
    "Astral Projection": "cleric;warlock;wizard",
    "Foresight": "bard;druid;warlock;wizard",
    "Gate": "cleric;sorcerer;wizard",
    "Imprisonment": "warlock;wizard",
    "Mass Heal": "cleric",
    "Meteor Swarm": "sorcerer;wizard",
    "Power Word Heal": "bard;cleric",
    "Power Word Kill": "bard;sorcerer;warlock;wizard",
    "Prismatic Wall": "bard;wizard",
    "Shapechange": "druid;wizard",
    "Storm of Vengeance": "druid",
    "Time Stop": "sorcerer;wizard",
    "True Polymorph": "bard;warlock;wizard",
    "True Resurrection": "cleric;druid",
    "Weird": "wizard",
    "Wish": "sorcerer;wizard",
}

# PHB-only rows where the assignment relies on a 2024 class-list CHANGE
# I'm less than fully certain about — flagged for manual spot-check.
VERIFY = {
    "Color Spray",              # Bard added in 2024?
    "Entangle",                 # Ranger added in 2024?
    "Blindness/Deafness",       # Cleric dropped in 2024?
    "Meld into Stone",          # Ranger added in 2024?
    "Conjure Woodland Beings",  # Ranger dropped in 2024?
    "Divination",               # Druid + Wizard added in 2024?
    "Dominate Beast",           # Ranger added in 2024?
    "Creation",                 # Bard added in 2024? (kept off)
    "Mislead",                  # Warlock added in 2024?
    "Flesh to Stone",           # Warlock dropped; Druid/Sorcerer added?
    "Sunbeam",                  # Cleric added in 2024?
    "Prismatic Spray",          # Bard added in 2024?
    "Antipathy/Sympathy",       # Bard added in 2024?
    "Prismatic Wall",           # Bard added in 2024?
}

with open(MASTER, newline="") as f:
    rows = list(csv.DictReader(f))

missing = [r["name"] for r in rows if r["name"] not in C]
if missing:
    raise SystemExit(f"no class mapping for: {missing}")
extra = set(C) - {r["name"] for r in rows}
if extra:
    raise SystemExit(f"mappings with no master-list row: {sorted(extra)}")

fieldnames = ["name", "srd_name", "level", "school", "classes",
              "source", "tier", "status", "files", "notes"]
for r in rows:
    r["classes"] = C[r["name"]]
    if r["name"] in VERIFY:
        note = r.get("notes") or ""
        r["notes"] = (note + "; " if note else "") + "classes: verify"

with open(MASTER, "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=fieldnames)
    w.writeheader()
    w.writerows(rows)

print(f"wrote {len(rows)} rows; {len(VERIFY)} flagged 'classes: verify'")
